
import { Navbar } from '@/components'
import './globals.css'

export const metadata = {
  title: 'Nikhil Shekhawat - portfolio',
  description: 'a portfolio generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  )
}
