const projects = [
	{
		id: "1",
		projectName: "Crypto Dashboard",
		aboutProject: "To show real time cryptocurrency data ",
		shortDesc: [
			"Real-time Cryptocurrency Data: Integrate Coingecko API to fetch real-time data of various cryptocurrencies",
			"Watchlist: Allow users to create a personalized watchlist of favorite cryptocurrencies",
			"Recent List: Show a list of recently viewed cryptocurrencies",
			"Currency Selection: Provide the ability to choose the preferred currency for data display",
			"Crypto Chart: Implement different types of charts (horizontal barchart, vertical barchart, line chart)",
			"Comparison Feature: Enable users to compare the performance of two cryptocurrencies on the same chart",
			"Interactive Charts: Incorporate zooming and panning functionalities in the charts",
			"Historical Data: Allow users to view historical price data for cryptocurrencies",
			"Responsive Design: Ensure the dashboard is responsive across devices",
			"User Preferences: Provide customization options for users to set default settings",
			"Error Handling: Implement proper error handling for data retrieval and API connectivity",
			"Data Refresh: Include automatic data refresh mechanism to keep cryptocurrency data up to date",
		],
		status: "",
		overview:
			"Crypto Currency Dashboard is a web application that allows users to monitor real-time data of various cryptocurrencies. Built with React.js, Redux, and Tailwind CSS, this dashboard provides a user-friendly interface for tracking and analyzing cryptocurrency information.The frontend of the application, developed using React.js, offers a responsive and intuitive design. With the help of Tailwind CSS, the styling is customizable and consistent across different components. Redux is employed for centralized state management, enabling efficient data flow and easy access to cryptocurrency data.The application fetches real-time cryptocurrency data from reliable APIs CoinGecko . Through Fetch, it retrieves information including current prices, market cap, trading volume, and price trends for a wide range of cryptocurrencies.Users can view the real-time data on the dashboard, which displays a list of cryptocurrencies sortable by various criteria. Detailed information about each cryptocurrency, such as historical price charts and additional metrics, can be accessed on separate pages. The dashboard provides an intuitive and informative visual representation of the cryptocurrency market.To enhance the user experience, the application can incorporate features like price alerts. Users can set customized notifications for specific cryptocurrencies, receiving alerts when prices surpass certain thresholds. This functionality helps users stay informed about market movements and make informed decisions.Additionally, the application can include a user authentication system, allowing users to create accounts, save personalized settings, and access their dashboard preferences from any device. Social features such as user-generated content, comments, and a community forum can also be implemented, facilitating knowledge sharing and discussions among users.Crypto Currency Dashboard offers a comprehensive and convenient platform for users to monitor and analyze cryptocurrency data in real-time. Its modern frontend, powered by React.js, Redux, and Tailwind CSS, ensures a visually appealing and responsive interface. With features like price alerts and potential social elements, users can stay updated and actively engage with the dynamic cryptocurrency market.",
		toolsUsed: [
			"React.js",
			" Javascript ",
			"Redux-toolkit",
			"redux-thunk",
			"TailwindCSS",
			"CoinGecko API",
			"Chart.js",
		],
		imgURL: "/images/crypto.jpg",
		detailedImgURL: ["/images/crypto.svg"],
		github: "https://github.com/nikhil-223/cryptocurrency-project",
		projectURL: "https://crypto-currency-board.netlify.app",
	},
	{
		id: "2",
		projectName: "Talkr",
		aboutProject: "A chatting app",
		shortDesc: [
			"User Registration and Login: Users can create an account and securely log in to the app using their credentials.",
			"Profile Customization: Users can personalize their profiles by uploading a profile picture.",
			"Real-time Messaging: Users can send and receive messages in real time, allowing instant communication.",
			"Message Deletion: Users have the ability to delete their own messages, providing control over their conversations.",
			"Group Chat: Users can create and join groups to engage in multi-participant conversations.",
			"Online Status: Users can see the online status of their contacts to know who is currently available for chat.",
			"Notifications: Users receive notifications for new messages and group invitations.",
			"Search Functionality: Users can search for other users or groups within the app.",
			"Emojis and Stickers: Users can express themselves using a wide range of emojis and stickers in their conversations.",
			"Multimedia Sharing: Users can share images, videos, and other files with their contacts or groups.",
			"Read Receipts: Users can see if their sent messages have been read by the recipients.",
			"Typing Indicators: Users can see when the other person is typing a message.",
			"Account Settings: Users can manage their account settings, including profile information, privacy preferences, and notification preferences.",
		],
		status: "In progress",
		overview: "overview",
		toolsUsed: [
			"React.js",
			" Javascript ",
			"Redux-toolkit",
			"redux-thunk",
			"node.js",
			"mongodb",
			"express.js",
			"socket.io",
			"json web token",
		],
		imgURL: "/images/chatApp.png",
		detailedImgURL: ["/images/crypto.svg"],
		github: "https://github.com/nikhil-223/chatting-app",
		projectURL: "https://chatttingapp.netlify.app",
	},
	{
		id: "3",
		projectName: "Inotepad",
		aboutProject: "A note making app",
		shortDesc: [
			"Real-time Cryptocurrency Data: Integrate Coingecko API to fetch real-time data of various cryptocurrencies",
			"Watchlist: Allow users to create a personalized watchlist of favorite cryptocurrencies",
			"Recent List: Show a list of recently viewed cryptocurrencies",
			"Currency Selection: Provide the ability to choose the preferred currency for data display",
			"Crypto Chart: Implement different types of charts (horizontal barchart, vertical barchart, line chart)",
			"Comparison Feature: Enable users to compare the performance of two cryptocurrencies on the same chart",
			"Interactive Charts: Incorporate zooming and panning functionalities in the charts",
			"Historical Data: Allow users to view historical price data for cryptocurrencies",
			"Responsive Design: Ensure the dashboard is responsive across devices",
			"User Preferences: Provide customization options for users to set default settings",
			"Error Handling: Implement proper error handling for data retrieval and API connectivity",
			"Data Refresh: Include automatic data refresh mechanism to keep cryptocurrency data up to date",
		],
		status: "In progress",
		overview: "overview",
		toolsUsed: [
			"React.js",
			" Javascript ",
			"contextAPI",
			"node.js",
			"mongodb",
			"express.js",
			"socket.io",
			"json web token",
		],
		imgURL: "/images/inotepad.png",
		detailedImgURL: ["/images/inotepad1.svg"],
		github: "https://github.com/nikhil-223/inotepad",
		projectURL: "https://inotepad.netlify.app",
	},
	{
		id: "4",
		projectName: "Movie booking backend",
		aboutProject: "an alma better capstone project",
		shortDesc: [
			"Real-time Cryptocurrency Data: Integrate Coingecko API to fetch real-time data of various cryptocurrencies",
			"Watchlist: Allow users to create a personalized watchlist of favorite cryptocurrencies",
			"Recent List: Show a list of recently viewed cryptocurrencies",
			"Currency Selection: Provide the ability to choose the preferred currency for data display",
			"Crypto Chart: Implement different types of charts (horizontal barchart, vertical barchart, line chart)",
			"Comparison Feature: Enable users to compare the performance of two cryptocurrencies on the same chart",
			"Interactive Charts: Incorporate zooming and panning functionalities in the charts",
			"Historical Data: Allow users to view historical price data for cryptocurrencies",
			"Responsive Design: Ensure the dashboard is responsive across devices",
			"User Preferences: Provide customization options for users to set default settings",
			"Error Handling: Implement proper error handling for data retrieval and API connectivity",
			"Data Refresh: Include automatic data refresh mechanism to keep cryptocurrency data up to date",
		],
		status: "",
		overview: "overview",
		toolsUsed: [
			"React.js",
			"Next.js",
			" Javascript ",
			"node.js",
			"express.js",
			"mongodb",
		],
		imgURL: "/images/BookMyShow.png",
		detailedImgURL: ["/images/bookmyshow1.svg"],
		github: "https://github.com/nikhil-223/bookmyshow-project-server",
		projectURL: "https://bookmyshow-project-client.vercel.app",
	},
	{
		id: "5",
		projectName: "Noted",
		aboutProject: "A note making app created using Next.js",
		shortDesc: [
			"Real-time Cryptocurrency Data: Integrate Coingecko API to fetch real-time data of various cryptocurrencies",
			"Watchlist: Allow users to create a personalized watchlist of favorite cryptocurrencies",
			"Recent List: Show a list of recently viewed cryptocurrencies",
			"Currency Selection: Provide the ability to choose the preferred currency for data display",
			"Crypto Chart: Implement different types of charts (horizontal barchart, vertical barchart, line chart)",
			"Comparison Feature: Enable users to compare the performance of two cryptocurrencies on the same chart",
			"Interactive Charts: Incorporate zooming and panning functionalities in the charts",
			"Historical Data: Allow users to view historical price data for cryptocurrencies",
			"Responsive Design: Ensure the dashboard is responsive across devices",
			"User Preferences: Provide customization options for users to set default settings",
			"Error Handling: Implement proper error handling for data retrieval and API connectivity",
			"Data Refresh: Include automatic data refresh mechanism to keep cryptocurrency data up to date",
		],
		status: "",
		overview: "overview",
		toolsUsed: [
			"Next.js",
			"next-auth.js",
			"google cloud",
			"React.js",
			" Javascript ",
			"TailwindCSS",
		],
		imgURL: "/images/Noted.png",
		detailedImgURL: ["/images/crypto.svg"],
		github: "https://github.com/nikhil-223/noted",
		projectURL: "https://tobenoted.vercel.app",
	},
	{
		id: "6",
		projectName: "Portfolio",
		aboutProject: "My personal portfolio website",
		shortDesc: [
			"Real-time Cryptocurrency Data: Integrate Coingecko API to fetch real-time data of various cryptocurrencies",
			"Watchlist: Allow users to create a personalized watchlist of favorite cryptocurrencies",
			"Recent List: Show a list of recently viewed cryptocurrencies",
			"Currency Selection: Provide the ability to choose the preferred currency for data display",
			"Crypto Chart: Implement different types of charts (horizontal barchart, vertical barchart, line chart)",
			"Comparison Feature: Enable users to compare the performance of two cryptocurrencies on the same chart",
			"Interactive Charts: Incorporate zooming and panning functionalities in the charts",
			"Historical Data: Allow users to view historical price data for cryptocurrencies",
			"Responsive Design: Ensure the dashboard is responsive across devices",
			"User Preferences: Provide customization options for users to set default settings",
			"Error Handling: Implement proper error handling for data retrieval and API connectivity",
			"Data Refresh: Include automatic data refresh mechanism to keep cryptocurrency data up to date",
		],
		status: "",
		overview: "overview",
		toolsUsed: [
			"Next.js",
			"React.js",
			" Javascript ",
			"TailwindCSS",
			"Framer motion",
		],
		imgURL: "/images/Portfolio.png",
		detailedImgURL: ["/images/crypto.svg"],
		github: "https://github.com/nikhil-223/myPortfolio",
		projectURL: "https://nikhilshekhawat.netlify.app",
	},
	{
		id: "7",
		projectName: "CSS Challenges",
		aboutProject: "Some css challenges",
		shortDesc: [
			"Real-time Cryptocurrency Data: Integrate Coingecko API to fetch real-time data of various cryptocurrencies",
			"Watchlist: Allow users to create a personalized watchlist of favorite cryptocurrencies",
			"Recent List: Show a list of recently viewed cryptocurrencies",
			"Currency Selection: Provide the ability to choose the preferred currency for data display",
			"Crypto Chart: Implement different types of charts (horizontal barchart, vertical barchart, line chart)",
			"Comparison Feature: Enable users to compare the performance of two cryptocurrencies on the same chart",
			"Interactive Charts: Incorporate zooming and panning functionalities in the charts",
			"Historical Data: Allow users to view historical price data for cryptocurrencies",
			"Responsive Design: Ensure the dashboard is responsive across devices",
			"User Preferences: Provide customization options for users to set default settings",
			"Error Handling: Implement proper error handling for data retrieval and API connectivity",
			"Data Refresh: Include automatic data refresh mechanism to keep cryptocurrency data up to date",
		],
		status: "In progress",
		overview: "overview",
		toolsUsed: ["React.js", " Javascript ", "CSS"],
		imgURL: "/images/cssChallenges.png",
		detailedImgURL: ["/images/crypto.svg", "/images/crypto.svg"],
		github: "https://github.com/nikhil-223/css-challenge-react",
		projectURL: "https://css-challengesbynikhil.netlify.app/",
	},
];

export default projects;
